name: E2E Tests

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  e2e_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.16.0

      - name: Install Dependencies
        run: npm install

      - name: Run E2E Tests
        run: npm run start:ci



